version: '3'
services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - ./data:/var/lib/postresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    command: -p 5432
  api:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 4000:4000
    expose:
      - 4000
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
